# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_manage', '0001_initial'),
        ('watch_buy', '0002_auto_20190524_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(editable=False)),
                ('quality', models.FloatField()),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_buy.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_manage.User')),
            ],
            options={
                'verbose_name': '这是一条评论',
                'verbose_name_plural': '这是一条评论',
            },
        ),
    ]
