# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('after_sold', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '图书评论', 'verbose_name_plural': '图书评论'},
        ),
    ]
