# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('after_sold', '0003_auto_20190524_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论发布时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_buy.Goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='quality',
            field=models.FloatField(verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_manage.User', verbose_name='用户'),
        ),
    ]
