# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='城市编号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='detail_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='账户余额'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='QQ号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='邮编'),
        ),
    ]
