# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-19 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_manage', '0002_auto_20190519_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city_num',
            field=models.IntegerField(null=True),
        ),
    ]
