# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-21 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_manage', '0003_user_city_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.FloatField(null=True),
        ),
    ]
