# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-23 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_manage', '0004_user_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.IntegerField(default=0, verbose_name='账户状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=20, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city_num',
            field=models.IntegerField(null=True, verbose_name='城市编号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='detail_address',
            field=models.CharField(max_length=255, null=True, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='邮箱地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.FloatField(null=True, verbose_name='账户余额'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.CharField(max_length=20, null=True, verbose_name='QQ号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='studentID',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=20, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(max_length=20, null=True, verbose_name='邮编'),
        ),
    ]
