# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_manage', '0005_auto_20190523_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.IntegerField(default=0, verbose_name='用户状态'),
        ),
    ]
