# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_manage', '0006_user_is_banned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_banned',
            field=models.IntegerField(default=0, verbose_name='账户状态'),
        ),
    ]
