# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-15 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '购物车信息',
                'verbose_name_plural': '购物车信息',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('GoodISBN', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('GoodName', models.CharField(max_length=255, unique=True)),
                ('GoodPrice', models.FloatField()),
                ('GoodAuthor', models.CharField(max_length=255, null=True)),
                ('GoodIntro', models.TextField(null=True)),
                ('GoodRemain', models.IntegerField(default=0)),
                ('GoodDiscount', models.FloatField(default=1.0)),
                ('IsForSale', models.IntegerField(default=0)),
                ('IsNew', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='GoodsPic',
            fields=[
                ('PicId', models.AutoField(primary_key=True, serialize=False)),
                ('GoodPic', models.ImageField(upload_to='')),
                ('GoodISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_buy.Goods')),
            ],
            options={
                'verbose_name': '商品图像',
                'verbose_name_plural': '商品图像',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='GoodID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_buy.Goods'),
        ),
        migrations.AddField(
            model_name='cart',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_manage.User'),
        ),
    ]
