# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_buy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='IsReturn',
            field=models.IntegerField(default=0, verbose_name='是否退回'),
        ),
        migrations.AlterField(
            model_name='order',
            name='qq',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='收货人QQ'),
        ),
    ]
