# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_buy', '0002_auto_20190524_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='Category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='GoodAuthor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='GoodIntro',
            field=models.TextField(blank=True, null=True, verbose_name='商品介绍'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='Intro_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='介绍图片'),
        ),
        migrations.AlterField(
            model_name='order',
            name='IsCancle',
            field=models.IntegerField(default=0, verbose_name='是否取消订单'),
        ),
        migrations.AlterField(
            model_name='order',
            name='IsCancled',
            field=models.IntegerField(default=0, verbose_name='是否完成退款'),
        ),
    ]
