# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-30 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_buy', '0003_auto_20190528_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='Edition',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='Pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='PrintDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='PublishDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='Publisher',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='Size',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
