# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-21 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_buy', '0006_auto_20190521_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='count',
        ),
        migrations.AddField(
            model_name='ordergood',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
