# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-23 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_buy', '0007_auto_20190521_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='IsCompleted',
            field=models.IntegerField(default=0),
        ),
    ]
