# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_buy', '0007_auto_20190521_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='GoodID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_buy.Goods', verbose_name='商品信息'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Qty',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_manage.User', verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='GoodAuthor',
            field=models.CharField(max_length=255, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='GoodDiscount',
            field=models.FloatField(default=1.0, verbose_name='折扣'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='GoodISBN',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='GoodIntro',
            field=models.TextField(null=True, verbose_name='商品介绍'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='GoodName',
            field=models.CharField(max_length=255, unique=True, verbose_name='书籍名称'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='GoodPrice',
            field=models.FloatField(verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='GoodRemain',
            field=models.IntegerField(default=0, verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='Intro_pic',
            field=models.ImageField(null=True, upload_to='', verbose_name='介绍图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='IsForSale',
            field=models.IntegerField(default=0, verbose_name='是否打折'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='IsNew',
            field=models.IntegerField(default=0, verbose_name='是否新品'),
        ),
        migrations.AlterField(
            model_name='goodspic',
            name='GoodISBN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_buy.Goods', verbose_name='图书信息'),
        ),
        migrations.AlterField(
            model_name='goodspic',
            name='GoodPic',
            field=models.ImageField(upload_to='', verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='goodspic',
            name='PicId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='图片ID'),
        ),
    ]
