# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_buy', '0008_auto_20190523_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='IsCancle',
            field=models.IntegerField(default=0, verbose_name='是否取消'),
        ),
        migrations.AlterField(
            model_name='order',
            name='IsCancled',
            field=models.IntegerField(default=0, verbose_name='是否退货'),
        ),
        migrations.AlterField(
            model_name='order',
            name='IsHandled',
            field=models.IntegerField(default=0, verbose_name='是否处理'),
        ),
        migrations.AlterField(
            model_name='order',
            name='IsShipped',
            field=models.IntegerField(default=0, verbose_name='是否发货'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, verbose_name='收货人地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.DateTimeField(verbose_name='下单时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='qq',
            field=models.CharField(max_length=15, verbose_name='收货人QQ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipdate',
            field=models.DateTimeField(null=True, verbose_name='发货时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='telephone',
            field=models.CharField(max_length=25, verbose_name='收货人电话'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_manage.User', verbose_name='下单用户'),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(max_length=20, verbose_name='收货人姓名'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.CharField(max_length=25, verbose_name='收货人邮编'),
        ),
        migrations.AlterField(
            model_name='ordergood',
            name='count',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='ordergood',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_buy.Goods', verbose_name='商品信息'),
        ),
        migrations.AlterField(
            model_name='ordergood',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_buy.Order', verbose_name='订单号'),
        ),
    ]
