# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-24 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_buy', '0009_goods_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Comment',
            field=models.CharField(default='fsdadf', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='IsReturn',
            field=models.IntegerField(default=0),
        ),
    ]
